[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[env]
WIFI_SSID = "Your Wifi SSID"
WIFI_PASS = "Your password"

# Below environment variables are optional
ESP_LOGLEVEL = "INFO"
LOG_SERVER_PORT = "3030"
WIFI_STACK_SEED = "1234"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core"]
